name: build_release

on:
  push:
    branches: [latest]
    tags: ["*"]
  pull_request:
    branches: [latest]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# For softprops/action-gh-release
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-lang-chinese texlive-fonts-recommended texlive-latex-extra fonts-noto-cjk-extra

      - name: Build PDF
        run: |
          xelatex main.tex
          xelatex main.tex
          mkdir dist
          mv main.pdf dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/main.pdf

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/main.pdf
